apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    app: nginx-app

  template:
    metadata:
      name: nginx-app
      labels:
        app: nginx-app
    
    spec:
      containers:
        - name: nginx-app
    
          image: nginx
          ports:
            - containerPort: 8080
