apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-controller-nginx
spec:
  replicas: 4
  template:
    metadata:      
      name: rc-nginx
      labels:
        name: rc-template-nginx
    spec:
      containers:
        - name: rc-nginx
          image: nginx
    