apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-fe-1
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-rs
  template:
    metadata:
      name: nginx-rs-fe
      labels:
        app: nginx-rs
    spec:
      containers:
        - name: nginx-img
          image: nginx

