apiVersion: v1
kind: Service
metadata:
  name: backend-app
  labels:
    app: node-backend-app
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001

